project_id = "bhioxffiqadhbbyaakpm"

[functions.send-confirmation]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.foia-chat]
verify_jwt = false

[functions.notify-status-change]
verify_jwt = false
